# Base configs
baseurl: "https://doucette.photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Doucette Photoagraphy"
subtitle: "See the world through my eyes!"
author: "Daniel Doucette"
header:
 title: "Photography"
 subtitle: "by Doucette Photography"
footer:
 name: "Hey there, my name is Daniel"
 bio: "Photographs from Doucette Photography"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/rddoucette"
  twitter: "https://www.twitter.com/ddoucette"
  instagram: "https://www.instagram.com/ddoucette"
  dribbble: "https://dribbble.com/ddoucette"
  linkedin: "https://in.linkedin.com/in/ddoucette"
  github: "https://www.github.com/ddoucette"
